package com.example.vectorcatalog;

import com.example.vectorcatalog.product.Product;
import com.example.vectorcatalog.product.ProductRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;

/**
 * Seeds sample products on startup if the products table is empty.
 *
 * Each save() triggers the DB embedding trigger — the Gemini API is called
 * for each product. This means startup takes a few extra seconds on first boot
 * (one Gemini API call per product). Subsequent restarts skip seeding.
 */
@Component
public class DataSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(DataSeeder.class);

    private final ProductRepository repository;

    public DataSeeder(ProductRepository repository) {
        this.repository = repository;
    }

    @Override
    public void run(ApplicationArguments args) {
        if (repository.count() > 0) {
            log.info("Products table already has data — skipping seed");
            return;
        }

        log.info("Seeding sample products (embeddings generated by DB trigger)...");

        List<Product> products = List.of(
                new Product("Eversummer Jacket",
                        "Lightweight breathable windbreaker for humid climates",
                        new BigDecimal("89.99")),
                new Product("Arctic Shield Parka",
                        "Heavy insulated jacket for extreme cold and blizzard conditions",
                        new BigDecimal("199.99")),
                new Product("Desert Runner Shorts",
                        "Ultra-light breathable shorts for hot and dry trail running",
                        new BigDecimal("49.99")),
                new Product("Mountain Storm Jacket",
                        "Waterproof hardshell for alpine conditions and heavy rain",
                        new BigDecimal("249.99")),
                new Product("Tropical Sun Hat",
                        "Wide brim hat with UV protection for beach and humid outdoor activities",
                        new BigDecimal("29.99")),
                new Product("Summit Fleece Pullover",
                        "Mid-layer merino wool fleece for cool mountain evenings",
                        new BigDecimal("119.99")),
                new Product("Coastal Rain Poncho",
                        "Packable waterproof poncho for beach towns and rainy coastal hikes",
                        new BigDecimal("39.99")),
                new Product("Urban Commuter Jacket",
                        "Slim-cut city jacket with water-resistant shell for daily commuting",
                        new BigDecimal("149.99"))
        );

        repository.saveAll(products);
        log.info("Seeded {} products with embeddings", products.size());
    }
}
